config/routes.rb
VirtualServerRoom::Application.routes.draw do

  resources :servers

  devise_for :users

  resources :points

   root :to => 'points#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)

    if user.role? :administrator
      can :manage, :all
    elsif user.role? :user
# роль пользователя на данный момент не выдается (не используется)
    elsif user.role? nil
      can :index, Point
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/point.rb
class Point < ActiveRecord::Base
  extend PointModule
  attr_accessible :description, :name, :owner, :coord_x1, :coord_y1, :coord_x2, :coord_y2, :ip, :os, :netname, :type_srv, :bond, :number_rack, :server_id, :position_in_rack

  validates :name, :owner, :coord_y1, :coord_x2, :coord_x1, :coord_y2, :ip, :os, :type_srv, presence: true
  validates :name, :owner, :ip, :os, length: {in: 7..35}
  validates :description, length: {in: 20..200}
  validates :coord_y2, :coord_x1, :coord_x2, :coord_y1, numericality: true

  belongs_to :server

  scope :points_view, ->(room_id) { where("server_id = ?", room_id).order("name ASC") }
  scope :point_bond, ->(point) { where('bond = ?', point) }

  def self.unload_point(gon,servers_room_id)
    gon.x1 = []
    gon.y1 = []
    gon.x2 = []
    gon.y2 = []
    Point.where('server_id = ?', servers_room_id).each do |p|
      gon.x1[p.id] = p.coord_x1
      gon.y1[p.id] = p.coord_y1
      gon.x2[p.id] = p.coord_x2
      gon.y2[p.id] = p.coord_y2
    end
  end
end

app/models/point_module.rb
module PointModule
  def user_access(gon,current_user)
    if current_user.present?
      gon.user_access = current_user.role_ids
    else
      gon.user_access = 0
    end
  end

  def reg_change(param)
    @reg_change = Server.first
    @reg_change.reg_change = param
    @reg_change.save
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
   attr_accessible :name, :role_ids

  has_and_belongs_to_many :users

end

app/models/server.rb
require 'file_size_validator'

class Server < ActiveRecord::Base
  attr_accessible :title, :image, :id

  has_many :points
  mount_uploader :image, ImageUploader

  validates :title, :image, presence: true
  validates :title, length: { in: 5..15}
  validates :image,
            :file_size => {
                :maximum => 3.megabytes.to_i
            }

end

app/models/user.rb
class User < ActiveRecord::Base

  before_create :setup_role

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :role_ids

  has_and_belongs_to_many :roles

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  private
  def setup_role
    if self.role_ids.empty?
      self.role_ids = [1]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_url
  end

end

app/controllers/points_controller.rb
class PointsController < ApplicationController

  load_and_authorize_resource :except => [:index]
  before_filter :find_point, :only => [:destroy, :update, :edit]

  # GET /points
  # GET /points.json
  def index
    @point = Point.new
    params_if()
    @reg_change = Server.first.reg_change
    Point.unload_point(gon,@@servers_room_id)
    Point.user_access(gon,current_user)

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /points/1/edit
  def edit

  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(params[:point])
    @point.server_id = @@servers_room_id

    respond_to do |format|
      if @point.save
        format.html { redirect_to root_path }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /points/1
  # PUT /points/1.json
  def update

    respond_to do |format|
      if @point.update_attributes(params[:point])
        format.html { redirect_to root_path }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy

    respond_to do |format|
      format.js
    end
  end

  private
  def find_point
    @point = Point.find(params[:id].to_i)
  end

  def params_if
    servers_room = params[:servers_room].to_i
    if servers_room.nonzero?
      @server = Server.find(servers_room)
      @points = Point.points_view(servers_room)
      @@servers_room_id = servers_room
    elsif params[:reg_change]
      Point.reg_change(params[:reg_change].to_i)
    elsif params[:point]
      @points = Point.point_bond(params[:point].to_i)
    else
      @server = Server.first
      @points = Point.points_view(1)
      @@servers_room_id = 1
    end
  end

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController

  load_and_authorize_resource
  before_filter :find_server, :except => [:index, :new, :create]

  # GET /servers
  # GET /servers.json
  def index
    # ограничим отображение количества серверных комнат (реальное кол-во серверных в организации 5)
    @servers = Server.limit(10)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.slim
    end
  end

  # GET /servers/1/edit
  def edit

  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to servers_path}
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to  servers_path}
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
    end
  end

  private
  def find_server
    @server = Server.find(params[:id].to_i)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/points_helper.rb
# coding: utf-8
module PointsHelper

  def edit_server(point)
    if (!current_user.nil? and current_user.role? :administrator)
      raw "<td><a href=\"points/#{point.id}/edit\">#{point.name}</a></td>"
    else
      raw "<th>#{point.name}</th>"
    end
  end

  def add_server
    if (!current_user.nil? and current_user.role? :administrator)
      raw "<p class=\"supple_srv\">&nbsp; Добавить сервер</p>"
    end
  end

  def server_type(type_srv)
   if (type_srv == 1)
     "Физический"
   elsif (type_srv == 2)
     "Виртуальный"
   else
     "NULL"
   end
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VirtualServerRoom</title>
  <%= include_gon %>
<!--  <%#= tinymce_assets %> -->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/points/_all_point.html.slim
div.all_show
  | &nbsp;
  div#search style="text-align: center;"
    div class="col-xs-12"
      input#ttt type="text" class="form-control input-sm" placeholder="Найти.."

  table class="table table-hover table-condensed"
    - @points.each do |point|
      tr.point id="#{point.bond}"
        td
        td style="font-size:12px; font-weight: bold;"
          = point.name
        td style="font-size:12px;"
          = point.ip
        td style="font-size:12px;"
          = point.owner
        - if current_user.nil?
          td style="font-size:12px;"
            = server_type(point.type_srv)
        - else
          td = link_to 'Изменить', edit_point_path(point)
          td = link_to 'Удалить', point, method: :delete, :remote => :true, :class => "del"

app/views/points/_form.html.slim
= form_for @point do |f|
  - if @point.errors.any?
    #error_explanation
      h2 = "#{pluralize(@point.errors.count, "error")} prohibited this point from being saved:"
      ul
        - @point.errors.full_messages.each do |message|
          li = message
  div.col-xs-12
    .field
      br
      = f.select :type_srv, options_for_select([['Тип сервера', 0], ['Физический', 1], ['Виртуальный', 2]], @point.type_srv), {}, html_options = {:class => "form-control"}
    .field
      = f.text_field :name, :placeholder => "Назначение..", :class => " form-control"
    .field
      = f.text_field :owner, :placeholder => "Ответственный..", :class => " form-control"
    .field
      = f.text_field :ip, :placeholder => "IP..", :class => " form-control"
    .field
      = f.text_field :netname, :placeholder => "Сетевое имя..", :class => " form-control"
    .field
      = f.text_field :os, :placeholder => "Операционная система..", :class => " form-control"
    .field
      span#addlink
        | Link |&nbsp;
      span#addbold
        | Bold
      br
      = f.text_area :description, :rows => "4", :placeholder => "Примечание..", :class => " form-control"
    .field
      = f.select :number_rack, options_for_select([['Укажите стойку', 0],['Шкаф: №1', 1], ['Шкаф: №2', 2], ['Шкаф: №3', 3], ['Шкаф: №4', 4], ['Шкаф: №5', 5]], @point.number_rack), {}, html_options = {:class => "form-control"}
    .field
      = f.text_field :position_in_rack, :placeholder => "Позиция в стойке U / № п\\п в блейде..", :class => "form-control"

    = f.hidden_field :server_id
    = f.hidden_field :bond
    = f.hidden_field :coord_x1
    = f.hidden_field :coord_y1
    = f.hidden_field :coord_x2
    = f.hidden_field :coord_y2
    br
    .actions = f.submit 'Сохранить', :class => "btn btn-default"

app/views/points/_head.html.slim
DOCTYPE html
div
  div class="navbar navbar-default"
    div class="nav navbar-nav"
      = link_to "Виртуальная серверная", root_path, :class=>"brand pull-left navbar-brand"
      ul class="nav navbar-nav"
        li class="divider-vertical"
        li
          - if user_signed_in?
            li
              a
                b = current_user.name
            div style="position:absolute; top:5%; left:870px;"
              = button_to 'Выйти', destroy_user_session_path, :method => :delete, :class => "btn btn-link"
          - else
            =link_to 'Войти', new_user_session_path

app/views/points/_show.html.slim
div.drag
  p
    | &nbsp;
  = add_server()
div.show
  table class="table table-hover table-condensed table-striped"
    tr style="font-size:12px;"
      td
      th Назначение
      th IP
      th Сетевое имя
      th Операционная система
      th Тип
      th Ответственный
      th Примечание
    - @points.each do |p|
      /- if p.bond == params[:point].to_i
      tr
        td
        = edit_server(p)
        td#ip class="#{p.ip}"
          = p.ip
        td#netname class="#{p.netname}"
          = p.netname
        td#os class="#{p.os}"
          = p.os
        td#type_srv class="#{p.type_srv}"
          = server_type(p.type_srv)
        td = p.owner
        td = sanitize(raw(p.description), tags: %w(a b), attributes: %w(href))

        input.rack type="hidden" value="#{p.number_rack}"
        input.position type="hidden" value="#{p.position_in_rack}"
        input.server_id type="hidden" value="#{p.server_id}"

        input.bond type="hidden" value="#{p.bond}"
        input.class-x1 type="hidden" value="#{p.coord_x1}"
        input.class-y1 type="hidden" value="#{p.coord_y1}"
        input.class-x2 type="hidden" value="#{p.coord_x2}"
        input.class-y2 type="hidden" value="#{p.coord_y2}"

app/views/points/_sign_in.html.slim
br
= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
  div class="col-xs-12"
    = f.email_field :email, :autofocus => true, :placeholder => "Email..", :class => "form-control"
    br
    = f.password_field :password, :placeholder => "Пароль..", :class => "form-control"
    br

    = f.submit "Войти", :class => "btn btn-default"

app/views/points/_sign_up.html.slim
br
= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
  div class="col-xs-12"
    = f.email_field :email, :autofocus => true, :placeholder => "Email..", :class => "form-control"
    br
    = f.text_field :name, :placeholder => "Имя..", :class => "form-control"
    br
    = f.password_field :password, :placeholder => "Пароль..", :class => "form-control"
    br
    = f.password_field :password_confirmation, :placeholder => "Повторите пароль..", :class => "form-control"
    br

    = f.submit "Зарегистрироваться", :class => "btn btn-default"

app/views/points/destroy.js.erb
//alert($(this).attr('id'));
//$(this.attr("id")).hide();

app/views/points/edit.html.slim
== render 'head'
div  style="position:absolute; top: 50px; left: 50px;"
  == render 'form'

app/views/points/index.html.slim
DOCTYPE html
div#main
  div class="navbar navbar-default"
    div class="nav navbar-nav"
      = link_to "Виртуальная серверная", root_path, :class=>"brand pull-left navbar-brand"
      ul class="nav navbar-nav"
        li class="divider-vertical"
        li
          div style="margin-top:7px;"
            = select_tag "servers", options_for_select(Server.limit(10).collect{|s| [s.title, s.id]}, :selected => params[:servers_room].to_i), :class => "servers_room form-control"
        li class="divider-vertical"
        li
          a#all_servers href="#" Список оборудования
        li class="divider-vertical"
        li
          - if user_signed_in?
            li
              a
                b = current_user.name
            li
              = link_to 'Серверные', servers_path
            li
              div style="margin-top:7px;"
                = select_tag "reg", options_for_select([["Регистрация выкл.",0],["Регистрация вкл.",1]], @reg_change), :class => "reg_change form-control"
            div style="position:absolute; top:5%; left:90%;"
              = button_to 'Выйти', destroy_user_session_path, :method => :delete, :class => "btn btn-link"
          - else
            - if (@reg_change == 1)
              li
                = link_to 'Регистрация', new_user_registration_path
            li
              a
                div.sign Войти

  fieldset#signin_menu
    = render ('sign_in')

  fieldset#reg_menu
    = render ('sign_up')

  div.container
    = image_tag(@server.image, :id => "img_server",  :class => "add", :usemap => "#test")

  map name="test"
    - @points.each do |point|
      area shape="rect" id="#{point.bond}" name="#{point.name}" coords="#{point.coord_x1},#{point.coord_y1}, #{point.coord_x2},#{point.coord_y2}" href="/"

  fieldset#show_menu

  fieldset#add_menu
    = render "form"

  fieldset#all_srv
    = render "all_point"

  div style="text-align:center;"
    br
    small Автор идеи - Костин Алексей. (с)

app/views/points/index.js.erb
$("#show_menu").html("<%= j render(:partial => 'points/show') %>");

$('p.supple_srv').click(function() {
// готовим вид менюшки для добавления сервера к имеющимся
  $("fieldset#add_menu").css("height","390px");
  $("input#point_position_in_rack").hide();
  $("select#point_number_rack, select#point_type_srv").hide();
// показываем ее
  $("fieldset#add_menu").show();
// даем потаскать
  $("fieldset#add_menu").draggable({ containment:'parent'});

  if (parseInt($('td#type_srv').attr("class")) == 1)
  {
      $('select#point_type_srv').val($('td#type_srv').attr("class"));

      $('input#point_bond').val($('input.bond').val());

      $('input#point_server_id').val($('input.server_id').val());
      $('input#point_position_in_rack').val($('input.position').val());
      $('select#point_number_rack').val($('input.rack').val());

      $('input#point_ip').val($('td#ip').attr("class"));
      $('input#point_os').val($('td#os').attr("class"));
      $('input#point_netname').val($('td#netname').attr("class"));

      $('input#point_coord_x1').val($('input.class-x1').val());
      $('input#point_coord_y1').val($('input.class-y1').val());
      $('input#point_coord_x2').val($('input.class-x2').val());
      $('input#point_coord_y2').val($('input.class-y2').val());
  } else {

      $('select#point_number_rack').val($('td#rack').attr("class"));
      $('input#point_server_id').val($('input.server_id').val());
      $('input#point_position_in_rack').val($('input.position').val());

      $('select#point_type_srv').val($('td#type_srv').attr("class"));

      $('input#point_bond').val($('input.bond').val());

      $('input#point_ip').val("");
      $('input#point_os').val("");
      $('input#point_netname').val("");

      $('input#point_coord_x1').val($('input.class-x1').val());
      $('input#point_coord_y1').val($('input.class-y1').val());
      $('input#point_coord_x2').val($('input.class-x2').val());
      $('input#point_coord_y2').val($('input.class-y2').val());
  }

});

app/views/points/new.html.slim
h1 New point

== render 'form'

= link_to 'Back', points_path

app/views/servers/_form.html.slim
= form_for @server do |f|
  div.col-xs-12
    = f.text_field :title, :placeholder => "Номер кабинета..", :class => " form-control"
    br
    div
      | Изображение:
      | &nbsp;
      = f.file_field :image
    div
      small * Размер загружаемого изображения: 1 157px × 750px
    br
    br
    .actions = f.submit 'Сохранить', :class => "btn btn-default"

br
= link_to 'На главную', root_path

app/views/servers/edit.html.slim
= render 'points/head'
div  style="position:absolute; top: 50px; left: 50px;"
  h5 Редактировать серверную:
  br
  = render 'form'

app/views/servers/index.html.slim
= render 'points/head'
div  style="position:absolute; top: 50px; left: 50px;"
  h4 Список доступных серверных:
  br
  table class="table table-hover"
    tr
      th ID
      th Местоположение
      th Изображение
      th
      th
    - @servers.each do |server|
      tr
        td = server.id
        td = server.title
        td
          img style='width:150px;' src= "#{server.image}"
        td = link_to 'Редактировать', edit_server_path(server)
        td = link_to 'Удалить', server, :confirm => 'Are you sure?', :method => :delete

  br
  = link_to 'На главную', root_path
  | &nbsp; | &nbsp;
  = link_to 'Добавить серверную', new_server_path

app/views/servers/new.html.slim
= render 'points/head'
div  style="position:absolute; top: 50px; left: 50px;"
  h5 Добавить серверную:
  br
  = render 'form'

app/views/servers/show.html.slim
p#notice = notice


= link_to 'Edit', edit_server_path(@server)
'|
= link_to 'Back', servers_path